# Projeto Final — Machine Learning e Visão Computacional

## Predição de Risco de Crédito

### Objetivo do projeto

Este projeto tem como objetivo desenvolver um pipeline completo de Machine Learning capaz de prever o risco de inadimplência de clientes de uma instituição financeira.

A variável alvo utilizada será `loan_status`:

- `0`: cliente adimplente;
- `1`: cliente inadimplente.

O desenvolvimento seguirá as seguintes etapas:

1. Coleta de Dados
2. Limpeza Estrutural e Exploração
3. Divisão dos Dados
4. Pré-processamento
5. Treinamento dos Modelos
6. Avaliação e Validação

Os algoritmos avaliados serão o K-Nearest Neighbors (KNN) e a Árvore de Decisão.

# 1. Coleta de Dados

Nesta etapa serão realizadas a importação das bibliotecas, a leitura da base de dados e uma inspeção inicial do conjunto de dados.

Nenhuma transformação ou exclusão será realizada neste momento. O objetivo é apenas verificar se a base foi carregada corretamente e compreender sua estrutura inicial.

## 1.1 Importação das Bibliotecas

In [285]:
# Manipulação e análise de dados
import pandas as pd
import numpy as np

# Visualização de dados
import matplotlib.pyplot as plt
import seaborn as sns

# Configurações visuais
sns.set_theme(style="whitegrid")

# Configuração para exibir todas as colunas do DataFrame
pd.set_option("display.max_columns", None)

## 1.2 Carregamento da Base de Dados

A base original está armazenada na pasta `data/raw`, preservando os dados brutos sem alterações.

O arquivo será carregado com a biblioteca Pandas e armazenado em um DataFrame chamado `df`.

In [286]:
# =====================================================
# Carregamento da base de dados
# =====================================================


# Caminho relativo do arquivo CSV
caminho_dados = "../data/raw/credit_risk_dataset.csv"

# Carregamento da base
df = pd.read_csv(caminho_dados)
print("Base carregada com sucesso!")

Base carregada com sucesso!

## 1.3 Inspeção Inicial dos Registros

In [287]:
print("Primeiros registros:")
display(df.head())
print("Ultimos registros:")
display(df.tail())
print("Registros aleatórios:")
display(df.sample(5, random_state=42))

Primeiros registros:

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

Ultimos registros:

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

Registros aleatórios:

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
14668,24,28000,OWN,6.0,HOMEIMPROVEMENT,B,10000,10.37,0,0.36,N,2
24614,27,64000,RENT,0.0,PERSONAL,C,10000,15.27,0,0.16,Y,10
11096,26,72000,MORTGAGE,10.0,EDUCATION,D,16000,NaN,0,0.22,N,3
10424,23,27996,RENT,7.0,DEBTCONSOLIDATION,A,10000,NaN,1,0.36,N,2
26007,30,44500,RENT,2.0,MEDICAL,E,13000,16.32,1,0.29,N,6

## 1.4 Dimensões do Dataset

In [288]:
linhas, colunas = df.shape
print(f"Quantidade de linhas : {linhas}")
print(f"Quantidade de colunas: {colunas}")

Quantidade de linhas : 32581
Quantidade de colunas: 12

## 1.5 Variáveis Disponíveis

In [289]:

for coluna in df.columns:
    print(coluna)

person_age
person_income
person_home_ownership
person_emp_length
loan_intent
loan_grade
loan_amnt
loan_int_rate
loan_status
loan_percent_income
cb_person_default_on_file
cb_person_cred_hist_length

### Primeiras observações

Após o carregamento da base foi possível verificar que o dataset contém informações relacionadas ao perfil financeiro dos clientes e às características dos empréstimos concedidos.

As variáveis incluem informações demográficas, renda anual, finalidade do empréstimo, classificação de crédito, taxa de juros e histórico financeiro.

A variável **loan_status** representa o alvo do problema de classificação, indicando se o cliente tornou-se inadimplente (1) ou permaneceu adimplente (0).

Nesta etapa foi confirmado que o arquivo foi carregado corretamente e que a estrutura da base está íntegra para prosseguirmos com a análise exploratória.

## 1.6 Auditoria Técnica Inicial

Antes de iniciar a análise exploratória é necessário compreender a estrutura interna do conjunto de dados.

Nesta etapa serão analisados:

- estrutura da base
- tipos das variáveis
- valores ausentes
- consistência dos dados

In [290]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  str
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  str
 5   loan_grade                  32581 non-null  str
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  str
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), str(4)
memory usage: 3.0 MB

In [291]:

df.dtypes.value_counts()
#permite prever o trabalho futuro, quantos Encoding precisaremos por exemplo

int64      5
str        4
float64    3
Name: count, dtype: int64

In [292]:
tipos = pd.DataFrame({

"Tipo":df.dtypes,

"Nulos":df.isnull().sum(),

"Percentual Nulos":round(df.isnull().mean()*100,2)

})

tipos

                               Tipo  Nulos  Percentual Nulos
person_age                    int64      0              0.00
person_income                 int64      0              0.00
person_home_ownership           str      0              0.00
person_emp_length           float64    895              2.75
loan_intent                     str      0              0.00
loan_grade                      str      0              0.00
loan_amnt                     int64      0              0.00
loan_int_rate               float64   3116              9.56
loan_status                   int64      0              0.00
loan_percent_income         float64      0              0.00
cb_person_default_on_file       str      0              0.00
cb_person_cred_hist_length    int64      0              0.00

### Análise da Auditoria Técnica

A auditoria técnica permitiu compreender a estrutura geral do conjunto de dados.

Foi possível identificar variáveis numéricas inteiras, variáveis numéricas contínuas e variáveis categóricas.

Também foram observadas colunas contendo valores ausentes, indicando que será necessária uma etapa de tratamento antes do treinamento dos modelos.

As variáveis categóricas deverão ser convertidas para representação numérica durante a fase de pré-processamento utilizando técnicas de Encoding.

Essa inspeção confirmou que a base apresenta estrutura compatível com problemas de classificação supervisionada.

# 2. Limpeza Estrutural e Exploração dos Dados

Nesta etapa será realizada uma investigação detalhada da qualidade dos dados.

O objetivo é compreender a distribuição das variáveis, identificar inconsistências e definir quais tratamentos serão necessários antes da construção dos modelos de Machine Learning.

## 2.1 - Detecção de valores duplicados

In [293]:
duplicados = df.duplicated().sum()

print(f"Quantidade de registros duplicados: {duplicados}")

Quantidade de registros duplicados: 165

### Investigação de Registros Duplicados

Foi realizada uma inspeção para identificar registros completamente duplicados na base de dados.

Registros duplicados podem introduzir viés estatístico, aumentando artificialmente a frequência de determinados perfis de clientes e influenciando o treinamento dos algoritmos.

Nesta etapa foi identificado o total de registros duplicados, cuja remoção será realizada apenas após a confirmação de que representam redundâncias reais.

## 2.2 - Detecção de valores Nulos

In [294]:
nulos = pd.DataFrame({

"Quantidade":df.isnull().sum(),

"Percentual":round(df.isnull().mean()*100,2)

})

nulos

                            Quantidade  Percentual
person_age                           0        0.00
person_income                        0        0.00
person_home_ownership                0        0.00
person_emp_length                  895        2.75
loan_intent                          0        0.00
loan_grade                           0        0.00
loan_amnt                            0        0.00
loan_int_rate                     3116        9.56
loan_status                          0        0.00
loan_percent_income                  0        0.00
cb_person_default_on_file            0        0.00
cb_person_cred_hist_length           0        0.00

### Investigação de Valores Ausentes

Foi realizada uma inspeção para identificar a presença de valores ausentes no conjunto de dados.

Os resultados permitirão definir, posteriormente, a estratégia de tratamento mais adequada para cada variável, considerando sua distribuição estatística e o impacto no treinamento dos modelos.

Nesta etapa nenhuma imputação foi realizada, pois o objetivo é apenas compreender a qualidade dos dados.

## 2.3 Análise Descritiva e Estatística

Nesta etapa será realizada uma análise estatística das variáveis presentes no conjunto de dados.

O objetivo é compreender a dimensão da base, os tipos das variáveis, as medidas de tendência central, a dispersão dos dados, os valores mínimos e máximos e os quartis.

Essa análise será utilizada para identificar possíveis assimetrias, inconsistências e indícios de valores extremos antes da construção dos gráficos exploratórios.

### Sumário Estatístico das Variáveis Numéricas

O método `describe()` será utilizado para calcular as principais medidas estatísticas das variáveis numéricas, incluindo média, desvio-padrão, mínimo, máximo e quartis.

In [295]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
person_age,32581.0,27.734600,6.348078,20.00,23.00,26.00,30.00,144.00
person_income,32581.0,66074.848470,61983.119168,4000.00,38500.00,55000.00,79200.00,6000000.00
person_emp_length,31686.0,4.789686,4.142630,0.00,2.00,4.00,7.00,123.00
loan_amnt,32581.0,9589.371106,6322.086646,500.00,5000.00,8000.00,12200.00,35000.00
loan_int_rate,29465.0,11.011695,3.240459,5.42,7.90,10.99,13.47,23.22
loan_status,32581.0,0.218164,0.413006,0.00,0.00,0.00,0.00,1.00
loan_percent_income,32581.0,0.170203,0.106782,0.00,0.09,0.15,0.23,0.83
cb_person_cred_hist_length,32581.0,5.804211,4.055001,2.00,3.00,4.00,8.00,30.00

### Sumário Estatístico das Variáveis Categóricas

As variáveis categóricas serão analisadas por meio da quantidade de valores preenchidos, número de categorias distintas, categoria mais frequente e frequência da categoria predominante.

In [296]:
df.describe(include="object").T

                           count unique        top   freq
person_home_ownership      32581      4       RENT  16446
loan_intent                32581      6  EDUCATION   6453
loan_grade                 32581      7          A  10777
cb_person_default_on_file  32581      2          N  26836

In [297]:
auditoria_estatistica = pd.DataFrame({
    "tipo_dado": df.dtypes,
    "quantidade_preenchida": df.notna().sum(),
    "quantidade_nulos": df.isna().sum(),
    "percentual_nulos": (df.isna().mean() * 100).round(2),
    "quantidade_unicos": df.nunique()
})

auditoria_estatistica

,tipo_dado,quantidade_preenchida,quantidade_nulos,percentual_nulos,quantidade_unicos
person_age,int64,32581,0,0.00,58
person_income,int64,32581,0,0.00,4295
person_home_ownership,str,32581,0,0.00,4
person_emp_length,float64,31686,895,2.75,36
loan_intent,str,32581,0,0.00,6
loan_grade,str,32581,0,0.00,7
loan_amnt,int64,32581,0,0.00,753
loan_int_rate,float64,29465,3116,9.56,348
loan_status,int64,32581,0,0.00,2
loan_percent_income,float64,32581,0,0.00,77
cb_person_default_on_file,str,32581,0,0.00,2
cb_person_cred_hist_length,int64,32581,0,0.00,29

### Decisão do Cientista de Dados — Análise Descritiva e Estatística

A análise desritiva demostra como os dados realmente se apresentam, enquando a estatística demonstra como eles de relacionam entre si

A análise descritiva confirmou que o conjunto de dados possui variáveis numéricas e categóricas relacionadas ao perfil dos clientes e às características dos empréstimos.

Na Análise estaística, a comparação entre média, mediana, quartis e valores máximos revelou que algumas variáveis apresentam valores máximos muito superiores ao terceiro quartil. Esse comportamento representa um indício de assimetria e possível presença de outliers.

As variáveis categóricas possuem um número limitado de categorias e deverão ser convertidas para formato numérico durante a etapa de pré-processamento.

As colunas com valores ausentes ainda não serão tratadas. A escolha entre média e mediana será realizada após a análise visual das distribuições, considerando que a média é sensível a valores extremos, enquanto a mediana é mais robusta.

Nenhum registro foi removido ou transformado nesta etapa.