# Projeto Final - Machine Learning e Visão Computacional

## Predição de Risco de Crédito

---

## Objetivo

Desenvolver um pipeline completo de Machine Learning capaz de prever clientes com risco de inadimplência, passando pelas etapas de coleta dos dados, exploração, limpeza, preparação, treinamento e avaliação dos modelos.

---

## Pipeline do Projeto

1. Coleta de Dados
2. Limpeza Estrutural e Exploração
3. Divisão dos Dados
4. Pré-processamento
5. Treinamento do Modelo
6. Avaliação e Validação

# 1. Coleta de Dados

Nesta etapa será realizada a importação das bibliotecas necessárias para o projeto, o carregamento da base de dados e uma primeira inspeção da estrutura do dataset.

## 1.1 Importação das Bibliotecas

In [55]:
# =====================================================
# Bibliotecas para manipulação de dados
# =====================================================

import pandas as pd
import numpy as np

# =====================================================
# Bibliotecas para visualização
# =====================================================

import matplotlib.pyplot as plt
import seaborn as sns

# =====================================================
# Configuração dos gráficos
# =====================================================

plt.style.use("ggplot")
sns.set_theme(style="whitegrid")

# =====================================================
# Configuração geral
# =====================================================

import warnings

warnings.filterwarnings("ignore")

## 1.2 Carregamento da Base de Dados

Nesta etapa será realizada a leitura do dataset utilizando a biblioteca Pandas e uma verificação inicial para garantir que os dados foram carregados corretamente.

In [56]:
# =====================================================
# Carregamento da base de dados
# =====================================================

caminho_dados = "../data/raw/credit_risk_dataset.csv"

df = pd.read_csv(caminho_dados)

In [57]:
print("Base carregada com sucesso!")
print("Primeiros registros:")
display(df.head())
print("Ultimos registros:")
display(df.tail())
print("Registros aleatórios:")
display(df.sample(5))

linhas, colunas = df.shape
print(f"Quantidade de linhas : {linhas}")
print(f"Quantidade de colunas: {colunas}")

for coluna in df.columns:
    print(coluna)

Base carregada com sucesso!
Primeiros registros:

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

Ultimos registros:

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

Registros aleatórios:

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
30987,48,50000,RENT,18.0,HOMEIMPROVEMENT,A,10000,9.63,0,0.20,N,14
24206,29,39000,RENT,1.0,HOMEIMPROVEMENT,D,10000,14.11,1,0.26,Y,7
26336,29,100000,MORTGAGE,13.0,MEDICAL,A,20000,6.54,0,0.20,N,5
22330,28,54080,MORTGAGE,7.0,HOMEIMPROVEMENT,B,13750,11.14,0,0.25,N,7
10165,26,65004,MORTGAGE,10.0,HOMEIMPROVEMENT,B,5000,11.58,0,0.08,N,3

Quantidade de linhas : 32581
Quantidade de colunas: 12
person_age
person_income
person_home_ownership
person_emp_length
loan_intent
loan_grade
loan_amnt
loan_int_rate
loan_status
loan_percent_income
cb_person_default_on_file
cb_person_cred_hist_length

### Primeiras observações

Após o carregamento da base foi possível verificar que o dataset contém informações relacionadas ao perfil financeiro dos clientes e às características dos empréstimos concedidos.

As variáveis incluem informações demográficas, renda anual, finalidade do empréstimo, classificação de crédito, taxa de juros e histórico financeiro.

A variável **loan_status** representa o alvo do problema de classificação, indicando se o cliente tornou-se inadimplente (1) ou permaneceu adimplente (0).

Nesta etapa foi confirmado que o arquivo foi carregado corretamente e que a estrutura da base está íntegra para prosseguirmos com a análise exploratória.

## 1.3 Auditoria Técnica do Dataset

Antes de iniciar a análise exploratória é necessário compreender a estrutura interna do conjunto de dados.

Nesta etapa serão analisados:

- estrutura da base
- tipos das variáveis
- memória utilizada
- valores ausentes
- consistência dos dados

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  str
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  str
 5   loan_grade                  32581 non-null  str
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  str
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), str(4)
memory usage: 3.0 MB

In [59]:

df.dtypes.value_counts()
#permite prever o trabalho futuro, quantos Encoding precisaremos por exemplo

int64      5
str        4
float64    3
Name: count, dtype: int64

In [60]:
tipos = pd.DataFrame({

"Tipo":df.dtypes,

"Nulos":df.isnull().sum(),

"Percentual Nulos":round(df.isnull().mean()*100,2)

})

tipos

                               Tipo  Nulos  Percentual Nulos
person_age                    int64      0              0.00
person_income                 int64      0              0.00
person_home_ownership           str      0              0.00
person_emp_length           float64    895              2.75
loan_intent                     str      0              0.00
loan_grade                      str      0              0.00
loan_amnt                     int64      0              0.00
loan_int_rate               float64   3116              9.56
loan_status                   int64      0              0.00
loan_percent_income         float64      0              0.00
cb_person_default_on_file       str      0              0.00
cb_person_cred_hist_length    int64      0              0.00

### Análise da Auditoria Técnica

A auditoria técnica permitiu compreender a estrutura geral do conjunto de dados.

Foi possível identificar variáveis numéricas inteiras, variáveis numéricas contínuas e variáveis categóricas.

Também foram observadas colunas contendo valores ausentes, indicando que será necessária uma etapa de tratamento antes do treinamento dos modelos.

As variáveis categóricas deverão ser convertidas para representação numérica durante a fase de pré-processamento utilizando técnicas de Encoding.

Essa inspeção confirmou que a base apresenta estrutura compatível com problemas de classificação supervisionada.

# 2. Limpeza Estrutural e Exploração dos Dados

Nesta etapa será realizada uma investigação detalhada da qualidade dos dados.

O objetivo é compreender a distribuição das variáveis, identificar inconsistências e definir quais tratamentos serão necessários antes da construção dos modelos de Machine Learning.

In [61]:
duplicados = df.duplicated().sum()

print(f"Quantidade de registros duplicados: {duplicados}")

Quantidade de registros duplicados: 165

### Investigação de Registros Duplicados

Foi realizada uma inspeção para identificar registros completamente duplicados na base de dados.

Registros duplicados podem introduzir viés estatístico, aumentando artificialmente a frequência de determinados perfis de clientes e influenciando o treinamento dos algoritmos.

Nesta etapa foi identificado o total de registros duplicados, cuja remoção será realizada apenas após a confirmação de que representam redundâncias reais.

In [62]:
nulos = pd.DataFrame({

"Quantidade":df.isnull().sum(),

"Percentual":round(df.isnull().mean()*100,2)

})

nulos

                            Quantidade  Percentual
person_age                           0        0.00
person_income                        0        0.00
person_home_ownership                0        0.00
person_emp_length                  895        2.75
loan_intent                          0        0.00
loan_grade                           0        0.00
loan_amnt                            0        0.00
loan_int_rate                     3116        9.56
loan_status                          0        0.00
loan_percent_income                  0        0.00
cb_person_default_on_file            0        0.00
cb_person_cred_hist_length           0        0.00

### Investigação de Valores Ausentes

Foi realizada uma inspeção para identificar a presença de valores ausentes no conjunto de dados.

Os resultados permitirão definir, posteriormente, a estratégia de tratamento mais adequada para cada variável, considerando sua distribuição estatística e o impacto no treinamento dos modelos.

Nesta etapa nenhuma imputação foi realizada, pois o objetivo é apenas compreender a qualidade dos dados.